#!/bin/bash
set -eu

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

final_path=$(ynh_app_setting_get $app final_path)
domain=$(ynh_app_setting_get $app domain)
APPDIR=$(ynh_app_setting_get $app appdir)
DATADIR=$(ynh_app_setting_get $app datadir)

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

workdir=$(pwd)
cd $APPDIR
tar -czf $workdir/appdir.gtar .
cd $workdir
ynh_backup ./appdir.gtar

#=================================================
# BACKUP THE APP DATA DIR
#=================================================

cd $DATADIR
tar -czf $workdir/datadir.gtar .
cd $workdir
ynh_backup ./datadir.gtar

#=================================================
# BACKUP THE CONFIGURATION
#=================================================

ynh_backup "/etc/systemd/system/$app.service" "conf/service"
ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf" "conf/nginx"
