#!/bin/bash
set -eu

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
is_public=$YNH_APP_ARG_IS_PUBLIC
language=$YNH_APP_ARG_LANG

app=$YNH_APP_INSTANCE_NAME
port=$(ynh_find_port 8081)
serviceuser=nexus

NEXUS_VERSION=3.4.0-02

workdir=$(pwd)

# Check domain/path availability
sudo yunohost app checkurl $domain -a $app
if [[ ! $? -eq 0 ]]; then
  ynh_die "domain not available"
fi

final_path="/var/lib/$app"
[[ -d $final_path ]] && ynh_die \
"The destination directory '$final_path' already exists.\
 You should safely delete it before installing this app."

# Define app's data directory
APPDIR="${final_path}/nexus-$NEXUS_VERSION"
DATADIR="${final_path}/sonatype-work"

# Save specific settings
ynh_app_setting_set $app final_path $final_path
ynh_app_setting_set $app is_public $is_public
ynh_app_setting_set $app datadir $DATADIR
ynh_app_setting_set $app appdir $APPDIR
ynh_app_setting_set $app serviceuser $serviceuser

#Install dependencies
sudo apt-get update
sudo apt-get install -y software-properties-common
sudo add-apt-repository "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main"
sudo apt-get update

# accept license to achieve silent install of oracle java (https://askubuntu.com/a/190674)
echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections

# install oracle 8 java
sudo apt-get install -y oracle-java8-installer

# Create destinations
sudo mkdir -p $APPDIR $DATADIR

# Copy and set systemd configuration
sed -i "s@#APPDIR#@$APPDIR@g"  ../conf/nexus.service
sudo cp ../conf/nexus.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable nexus

# Copy and set nginx configuration
nginx_conf="/etc/nginx/conf.d/${domain}.d/${app}.conf"
sed -i "s@#APP#@$app@g"          ../conf/nginx.conf
sed -i "s@#PATH#@$path@g"        ../conf/nginx.conf
sed -i "s@#PORT#@$port@g"        ../conf/nginx.conf
sed -i "s@#LOCATION#@${path:-/}@g" ../conf/nginx.conf
sed -i "s@#FINAL_PATH#@$final_path@g"  ../conf/nginx.conf

sudo cp ../conf/nginx.conf "$nginx_conf"

# download and extract
DOWNLOAD_URL=http://download.sonatype.com/nexus/3/nexus-$NEXUS_VERSION-unix.tar.gz
DOWNLOAD_FILE=nexus-$NEXUS_VERSION-unix.tar.gz
echo "Downloading $DOWNLOAD_FILE from $DOWNLOAD_URL."
sudo curl -s -L -o $final_path/$DOWNLOAD_FILE $DOWNLOAD_URL
sudo tar -xzf $final_path/$DOWNLOAD_FILE -C $APPDIR --strip-components=1 nexus-$NEXUS_VERSION
sudo tar -xzf $final_path/$DOWNLOAD_FILE -C $DATADIR --strip-components=1 sonatype-work
sudo rm -f $final_path/$DOWNLOAD_FILE

# configure nexus properties
sed -i "s@#PORT#@${port}@g" ../conf/nexus.properties
sed -i "s@#PATH#@${path:-/}@g" ../conf/nexus.properties
sudo mkdir -p $DATADIR/nexus3/etc
sudo cp ../conf/nexus.properties $DATADIR/nexus3/etc/nexus.properties

# Create user and chown paths
sudo useradd -d "$final_path" -M $serviceuser
sudo chown -R $serviceuser: $final_path
sudo chown -R $serviceuser: $DATADIR

sudo systemctl reload nginx
if [ "$is_public" = "Yes" ];
then
	ynh_app_setting_set "$app" skipped_uris "/"
fi

# first init start
sudo systemctl start nexus
# wait until init finished
timeout 90 grep -q 'Started Sonatype Nexus' <(tail -n +0 -F $DATADIR/nexus3/log/nexus.log)

sudo systemctl stop nexus

# preconfigured yunohost ldap via internal restore mechanism
# see --> https://books.sonatype.com/nexus-book/reference3/backup.html#backup-restore
sudo rm -rf $DATADIR/nexus3/db/accesslog
sudo rm -rf $DATADIR/nexus3/db/analytics
sudo rm -rf $DATADIR/nexus3/db/audit
sudo rm -rf $DATADIR/nexus3/db/component
sudo rm -rf $DATADIR/nexus3/db/config
sudo rm -rf $DATADIR/nexus3/db/security

sudo mkdir -p $DATADIR/nexus3/backup
sudo cp ../conf/bak/*.bak $DATADIR/nexus3/backup/

# restart to restore config
sudo systemctl start nexus
# wait until init finished
timeout 90 grep -q 'Started Sonatype Nexus' <(tail -F $DATADIR/nexus3/log/nexus.log)

# add to services
sudo yunohost service add nexus -l $DATADIR/nexus3/log/nexus.log

sudo yunohost app ssowatconf
