#!/bin/bash
set -u

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
final_path=$(ynh_app_setting_get $app final_path)

# unregister from yunohost services
sudo yunohost service remove nexus

# stop & disable service
sudo systemctl stop nexus
sudo systemctl disable nexus

sudo rm -rf $final_path
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf
sudo rm -f /etc/systemd/system/nexus.service
sudo userdel -r nexus

sudo systemctl daemon-reload
sudo systemctl reload nginx
