#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# IMPORT GENERIC HELPERS
source /usr/share/yunohost/helpers

# Load common variables and helpers
source ./experimental_helper.sh
source ./_common.sh

#=================================================
# STANDARD REMOVE
#=================================================

# Stop gogs
systemctl stop "$app".service
# Retrieve domain from app settings
domain=$(ynh_app_setting_get "$app" domain)

# Delete app directory and configurations
ynh_secure_remove "$final_path"
ynh_secure_remove "$DATADIR"

# Remove the app-specific logrotate config
ynh_remove_logrotate

# Remove nginx config
ynh_remove_nginx_config

# Remove gogs user and data
ynh_system_user_delete $appuser

# Remove init script
ynh_remove_systemd_config

# Remove monitor
yunohost service remove "$app"
