#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# IMPORT GENERIC HELPERS
source /usr/share/yunohost/helpers

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

# Load common variables and helpers
source ../settings/scripts/_common.sh

#=================================================
# LOAD SETTINGS
#=================================================

domain=$(ynh_app_setting_get $app domain)
path_url=$(ynh_app_setting_get $app path)
final_path=$(ynh_app_setting_get $app final_path)
appdir=$(ynh_app_setting_get $app appdir)
datadir=$(ynh_app_setting_get $app datadir)
serviceuser=$(ynh_app_setting_get $app serviceuser)

# Check domain/path availability
sudo yunohost app checkurl "${domain}${path}" -a "$app" || ynh_die

# Check destination directory
[[ -d $final_path ]] && ynh_die \
"The destination directory '$final_path' already exists.\
 You should safely delete it before restoring this app."

# Create destination
sudo mkdir -p $appdir $datadir

# Create user
sudo useradd -d "$appdir" -M $serviceuser

#=================================================
# STANDARD RESTORATION STEPS
#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================

sudo cp -a "conf/nginx" "/etc/nginx/conf.d/$domain.d/$app.conf"
sudo systemctl reload nginx

#=================================================
# RESTORE THE SYSTEMD CONFIGURATION
#=================================================
sudo cp -a "conf/service" "/etc/systemd/system/nexus.service"
sudo systemctl daemon-reload
sudo systemctl enable nexus

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================

sudo tar -xzf ./appdir.gtar -C $appdir
sudo tar -xzf ./datadir.gtar -C $datadir
sudo chown -R $serviceuser: $final_path

#=================================================
# START APP RELATED SERVICES
#=================================================

sudo systemctl start nexus
