#!/bin/bash
set -eu

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# GENERIC START
#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit on command errors and treat access to unset variables as an error
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
path=$(ynh_app_setting_get $app path)
path_url=$(ynh_app_setting_get $app path)
final_path=$(ynh_app_setting_get $app final_path)
APPDIR=$(ynh_app_setting_get $app appdir)
DATADIR=$(ynh_app_setting_get $app datadir)
serviceuser=$(ynh_app_setting_get $app serviceuser)

# Check domain/path availability
sudo yunohost app checkurl "${domain}${path}" -a "$app" || ynh_die

# Check destination directory
[[ -d $final_path ]] && ynh_die \
"The destination directory '$final_path' already exists.\
 You should safely delete it before restoring this app."

# Create destination
sudo mkdir -p $appdir $datadir

# Create user
sudo useradd -d "$appdir" -M $serviceuser

#=================================================
# STANDARD RESTORATION STEPS
#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================

sudo cp -a "conf/nginx" "/etc/nginx/conf.d/$domain.d/$app.conf"
sudo systemctl reload nginx

#=================================================
# RESTORE THE SYSTEMD CONFIGURATION
#=================================================
sudo cp -a "conf/service" "/etc/systemd/system/$app.service"
sudo systemctl daemon-reload
sudo systemctl enable $app

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================

sudo tar -xzf ./appdir.gtar -C $appdir
sudo tar -xzf ./datadir.gtar -C $datadir
sudo chown -R $serviceuser: $final_path

#=================================================
# START APP RELATED SERVICES
#=================================================

sudo systemctl start $app
